### PR TITLE
Pale Moon 27.1+ support

### PR DESCRIPTION
**Pull request by JustOff**
Based on [PMkit documentation draft v1.1](https://github.com/JustOff/pm27-sdk-addons/blob/master/PMkit.md), tested with [Pale Moon 27.1.0beta](http://www.palemoon.org/unstable/).

### CODE REVIEW

**Comment by JustOff** [comment]
Thank you for supporting Pale Moon! I would be most grateful if you could also publish updated version on AMO.

**Comment by zaidka** [comment]
The current code base is a dead-end for Firefox and I'm rewriting cliget using Web Extensions. Does/will Pale Moon support Web Extensions? How about e10s (e10s broke cliget)? I'm asking because I need to decide whether I need to keep two code bases or move to Web Extensions entirely.

**Comment by JustOff** [comment]
Pale Moon does not use e10s and currently there are no plans to support WebExtensions. If you would be so kind to support classic version of cliget I can assist you to host it at https://addons.palemoon.org/ (the signing of extensions is not required).

**Comment by Massimo-B** [comment]
Any news about that? I'm missing Cliget since migrating to Palemoon, though some old Cliget version was working for a while on Palemoon.

**Comment by Massimo-B** [comment]
Could you at least provide some .xpi build here? As supporting Palemoon is a major milestone, no matter how tiny the change was.

**Comment by zaidka** [comment]
There has been some fairly big changes since the last release that I need to review and clean up. Sorry but I just haven't had any time to work on it due to being overwhelmed with other work. I intend to get to it soon.

**Comment by Massimo-B** [comment]
Thank you very much. However I tried building that XPI, fetched some nodejs and jpm first, but it fails like this:

```
$ pwd
/home/mb/src/other/cliget

$ ls -al
total 36K
drwxr-xr-x 1 mb mb  132 Mär 23 07:26 ./
drwxr-xr-x 1 mb mb  264 Mär 23 08:02 ../
drwxr-xr-x 1 mb mb   82 Mär 23 07:21 data/
drwxr-xr-x 1 mb mb  122 Mär 23 07:21 .git/
-rw-r--r-- 1 mb mb   15 Mär 23 07:21 .gitignore
-rw-r--r-- 1 mb mb   18 Mär 23 07:21 .jshintrc
drwxr-xr-x 1 mb mb   48 Mär 23 07:21 lib/
-rw-r--r-- 1 mb mb  17K Mär 23 07:21 LICENSE.txt
-rw-r--r-- 1 mb mb 2,8K Mär 23 07:21 package.json
-rw-r--r-- 1 mb mb 1,4K Mär 23 07:21 README.md
drwxr-xr-x 1 mb mb   24 Mär 23 07:21 test/

$ /home/mb/src/other/jpm/bin/jpm xpi
module.js:472
    throw err;
    ^

Error: Cannot find module 'object-assign'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/mb/src/other/jpm/bin/jpm:4:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Pull request merged**
